language: node_js
node_js:
  - "16"
install:
    - npm install
deploy:
  - provider: codedeploy
    wait_until_deployed: true
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    bucket: "ci-express"
    key: latest/ci-app.zip
    bundle_type: zip
    application: "ci-express"
    deployment_group: "ci-express"
    region: "us-east-1"