language: node_js
node_js:
  - "16"
install:
    - npm install
deploy:
  - provider: codedeploy
    revision_type: github
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    application: "ci-express"
    deployment_group: "ci-express"
    region: "us-east-1"